// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"chat_with_me/app/web/app"
	"chat_with_me/app/web/conf"
	"chat_with_me/app/web/service/api"
	"chat_with_me/app/web/service/ws"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// wireApp init kratos application.
func WireApp(engine *gin.Engine) *app.App {
	logger := conf.NewLogger()
	indexController := api.NewIndexController(logger)
	wsController := ws.NewWsController(logger)
	appApp := app.NewApp(engine, indexController, wsController)
	return appApp
}
