// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"chat_with_me/app/web/app"
	"chat_with_me/app/web/data"
	"chat_with_me/app/web/log"
	"chat_with_me/app/web/service/api"
	"chat_with_me/app/web/service/ws"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

// wireApp init kratos application.
func WireApp(engine *gin.Engine) *app.App {
	logger := log.NewLogger()
	db := data.NewData()
	userRepo := data.NewUserRepo(db)
	indexController := api.NewIndexController(logger, userRepo)
	wsController := ws.NewWsController(logger)
	appApp := app.NewApp(engine, logger, indexController, wsController)
	return appApp
}
